using './main.bicep'

param location = 'southcentralus'
param eventHubNS = 'red-device-ehns'
param eventHubName = 'wheresmyhusband'
param keyVaultName = 'red-device-kv'
param aspName = 'red-device-asp'
param aspSku = 'EP1'
param lawName = 'red-device-law'
param appInsightsName = 'red-device-ai'
param functionAppName = 'red-device-funcapp'
param storageAccountName = 'reddevicestorage009'
param cosmosDbAccountName = 'red-device-cosmosdb'
param staticWebAppName = 'red-device-swa'
