name: Deploy Bicep

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read #This is required for actions/checkout
        id-token: write #This is required for requesting the JWT

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.ENTRA_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep
      run: |
        az deployment sub create \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --location 'southcentralus' \
            --name dotnetcore-wheresmydevice-deploy \
            --parameters ./iac/bicep/main.dev.bicepparam
